# Generated by Django 3.0.7 on 2020-06-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200616_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestate',
            name='state',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
