# Generated by Django 3.0.7 on 2020-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200618_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='profiles/no_image.png', null=True, upload_to='profiles'),
        ),
    ]
