# Generated by Django 3.0.7 on 2020-06-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200619_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='images/profiles/no_image.png', null=True, upload_to='images/profiles'),
        ),
    ]
