# Generated by Django 3.0.7 on 2020-06-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20200625_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, default='images/portfolio/no-image.png', null=True, upload_to='images/portfolio'),
        ),
    ]
