# Generated by Django 3.0.7 on 2020-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20200705_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='instag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
