# Generated by Django 3.0.7 on 2020-07-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
