# Generated by Django 3.0.7 on 2020-07-07 21:37

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20200707_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='published',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, size=[400, 400], upload_to='images/testimonials'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
