# Generated by Django 3.0.7 on 2020-07-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20200707_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=20)),
                ('appliance', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=20)),
                ('other_info', models.TextField(max_length=100)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenure', models.CharField(max_length=10)),
                ('frequency', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=40)),
                ('res_address', models.TextField(blank=True, max_length=300, null=True)),
                ('bus_address', models.TextField(blank=True, max_length=300, null=True)),
                ('mode_of_repymt', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantor_address', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantor_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created']},
        ),
    ]
