# Generated by Django 3.0.7 on 2020-07-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_auto_20200709_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeapplication',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
