# Generated by Django 3.0.7 on 2020-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20200711_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirycontact',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='enquirycontact',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
