# Generated by Django 3.0.7 on 2020-07-15 10:16

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_auto_20200711_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirycontact',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='images/portfolio/no-image.png', force_format=None, keep_meta=True, quality=85, size=[520, 400], upload_to='images/portfolio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/profiles/no_image.png', force_format=None, keep_meta=True, null=True, quality=85, size=[520, 400], upload_to='images/profiles'),
        ),
    ]
