# Generated by Django 3.0.7 on 2020-07-25 21:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20200725_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/profiles/no_image.png', force_format=None, keep_meta=True, null=True, quality=85, size=[520, 400], upload_to='images/profiles'),
        ),
    ]
