# Generated by Django 3.0.7 on 2020-07-25 22:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_auto_20200725_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/profiles/no_image.png', force_format=None, keep_meta=True, quality=85, size=[520, 400], upload_to='images/profiles'),
        ),
    ]
