# Generated by Django 3.0.7 on 2020-07-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_testimonial_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
