# Generated by Django 3.0.7 on 2020-07-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_testimonial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
