# Generated by Django 3.0.7 on 2020-07-31 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_portfolio_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='price',
            new_name='cost',
        ),
    ]
