# Generated by Django 3.0.7 on 2020-08-04 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.UUIDField(default=uuid.UUID('4e2dfb92-c902-48e7-92be-af86483815ab'), editable=False, unique=True),
        ),
    ]
