# Generated by Django 3.0.7 on 2020-08-04 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_auto_20200804_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='user',
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.UUIDField(default=uuid.UUID('ef4664d0-996b-411f-af58-a2d38816ba6b'), editable=False, unique=True),
        ),
    ]
