# Generated by Django 3.0.7 on 2020-08-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_auto_20200804_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
