# Generated by Django 3.0.7 on 2020-08-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_auto_20200804_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='c11a91611e262f6f68056d013873374775c677ea67ce500d53352ea8fabeaaa78b1d0d3e78a881710187c2e3b62e6d95e475742869a6ba219cb0f68b15462fe0bc6eaae1606638e272fbb0f14031463683aa753b3b7af8ed358b30f907c75ccff209d587503f2b9d065f0c7a416991d68f3fbfa591a2c2ce', max_length=200),
        ),
    ]
