# Generated by Django 3.0.7 on 2020-08-06 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_auto_20200804_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default='694ff1ade4d6074db1a0c6c7527c9f81fef34d02e04aba3f99a33a147845f4d1731064a1a76695afda07f03fa2964f2ede88aeb28497b97ca428479e34f6aeb3a30b77f7907d9b27066b90fd6e21b29876899314f24db814', max_length=200),
        ),
    ]
